# Change these first
owner: AppCenter-Snaptime # Your GitHub organization or username, where this repository lives
repo: snaptime-status # The name of this repository

sites:
  - name: Snaptime Swagger
    url: http://na2ru2.me:6308/swagger-ui/index.html
    
status-website:
  name: "Snaptime Status"
  navbar:
    - title: GitHub
      href: https://github.com/AppCenter-Snaptime/snaptime-status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
